name: continuous-integration

on: push

jobs:
  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: create env file
        run: |
          touch env.local
          echo "JWT_SECRET_KEY=yeahbuddy!!!!lightweightbaby!!wooooooo" >> env.local
      - name: run backend tests
        run: npm run integration-test
  # test-frontend:
  #   needs: test-backend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: run frontend tests
  #       run: npm run unit-test
  docker:
    needs: test-backend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build front and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:front"
          tags: sttay/yeahbuddyfront:latest
      - name: Build back and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:back"
          tags: sttay/yeahbuddyback:latest
